version: '3.8'

services:
  app:
    image: ubuntu
    environment:
      WAIT_HOSTS: kafka:9092
    working_dir: /opt
    volumes:
        - type: bind
          source: .
          target: /shared_1
        - type: bind
          source: /__w/test-actions/test-actions
          target: /shaerd_2

      #- ../test/test-conf-file.conf:/opt/test/test-conf-file.conf
    command: 
        - /bin/bash
        - -c
        - |
          ls -laR /shared_1
          ls -laR /shared_2
