version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      WAIT_HOSTS: kafka:9092
    working_dir: /opt
    command: 
        - /bin/bash
        - -c
        - |
          ls -laR /shared
