version: '3.8'

services:
  app:
    image: ubuntu
    environment:
      WAIT_HOSTS: kafka:9092
    working_dir: /opt
    volumes:
      - ./shaerd:/shared_1:rw
      - /__w/test-actions/test-actions/shared:/sahred_2:rw
      #- ../test/test-conf-file.conf:/opt/test/test-conf-file.conf
    command: 
        - /bin/bash
        - -c
        - |
          ls -laR /shared_1
          ls -laR /shared_2
