version: '3.8'

services:
  app:
    image: scr.svc.stanford.edu/eed-public/build-image/cpp-build-image/gcc-debian:12.2.0-bullseye
    environment:
      WAIT_HOSTS: kafka:9092
    working_dir: /opt
    volumes:
      - /__w/test-actions/test-actions/shared:/opt
      #- ../test/test-conf-file.conf:/opt/test/test-conf-file.conf
    command: 
        - /bin/bash
        - -c
        - |
          ls -laR /opt
          less /opt/
