name: Simulate Build

on: 
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'main'

jobs:
    build_ubuntu:
        runs-on: ubuntu-22.04
      
        steps:
            - uses: actions/checkout@v3
           
