name: Test EKG

on:
   push:
jobs:
    test_build:
        runs-on: ubuntu-latest
        container: docker
        steps:
            - uses: actions/checkout@v3
            - run: echo $PWD
            - run: |
                ls -la /__w/test-actions/test-actions/
                docker-compose -f docker/docker-compose.yml run --rm app
            - run: ls -laR